name: README builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Build README
      run: cd ./docs/; python build.py

    - name: Configure git
      run: git config user.name "Zahin Zaman"; git config user.email "alvii147@gmail.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "[Github Action Bot] Generated README.md" || exit 0
        git fetch origin main
        git push
